name: Build OneWifi Component in Native Environment

on:
  push:
    branches: [ main, 'release/**', develop ]
  pull_request:
    branches: [ main, 'release/**', topic/RDK*, develop ]
  workflow_dispatch:

concurrency:
  group: coverity-${{ github.ref }}
  cancel-in-progress: false   # don't kill an in-flight submission

permissions:
  contents: read

jobs:
  build-onewifi:
    name: Build OneWifi component in github rdkcentral for Coverity analysis
    runs-on: ubuntu-latest
    timeout-minutes: 30
    container:
      image: ghcr.io/rdkcentral/docker-rdk-ci:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Native-ish build for Coverity based on XB
        run: |

          # Trust the workspace
          git config --global --add safe.directory '*'
          # Pull the latest changes for the native build system
          git submodule update --init --recursive

          #Clone hostapd
          ORIG_DIR=$(pwd)
          mkdir -p $HOME/build/rdk-wifi-libhostap/source/hostap-2.11
          git clone https://git.w1.fi/hostap.git $HOME/build/rdk-wifi-libhostap/source/hostap-2.11
          cd $HOME/build/rdk-wifi-libhostap/source/hostap-2.11
          git checkout -b 2.11 4b8ac10cb77c3d4dbf7ccefbe697dc0578da374c
          cd ${ORIG_DIR}

          chmod +x build_tools_workflows/cov_docker_script/setup_dependencies.sh
          ./build_tools_workflows/cov_docker_script/setup_dependencies.sh ./cov_docker_script/component_config.json
          # Build component
          chmod +x build_tools_workflows/cov_docker_script/build_native.sh
          ./build_tools_workflows/cov_docker_script/build_native.sh ./cov_docker_script/component_config.json

        env:
          GITHUB_TOKEN: ${{ secrets.RDKCM_RDKE }}
